services:
  servidor-ssh:
    image: linuxserver/openssh-server
    container_name: servidor-backup
    environment:
      - PUID=1000
      - PGID=1000
      - USER_NAME=backup
      - USER_PASSWORD=123456
      - PASSWORD_ACCESS=true
    ports:
      - "2222:2222"
    volumes:
      - ./backup-recebido:/backup

